// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjd4mELmwtCaWJHUrb7l6x8pM1dbZfLE',
    appId: '1:497752609770:web:7677c0061131ef0aa51893',
    messagingSenderId: '497752609770',
    projectId: 'desh-crime-alert-e1b7a',
    authDomain: 'desh-crime-alert-e1b7a.firebaseapp.com',
    storageBucket: 'desh-crime-alert-e1b7a.firebasestorage.app',
    measurementId: 'G-LHCSSVXQBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIFZjYi5pJggx4q9XFkYfynEEuGf1Up8M',
    appId: '1:497752609770:android:4a01a959efb2a2a7a51893',
    messagingSenderId: '497752609770',
    projectId: 'desh-crime-alert-e1b7a',
    storageBucket: 'desh-crime-alert-e1b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JZgaEUpIACphqPnsRr98W9XgVTgi-AU',
    appId: '1:497752609770:ios:ad9c25cf9316c90ea51893',
    messagingSenderId: '497752609770',
    projectId: 'desh-crime-alert-e1b7a',
    storageBucket: 'desh-crime-alert-e1b7a.firebasestorage.app',
    iosClientId: '497752609770-01l1dgpbdk4i101escs0plcv06clqfuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.deshCrimeAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JZgaEUpIACphqPnsRr98W9XgVTgi-AU',
    appId: '1:497752609770:ios:ad9c25cf9316c90ea51893',
    messagingSenderId: '497752609770',
    projectId: 'desh-crime-alert-e1b7a',
    storageBucket: 'desh-crime-alert-e1b7a.firebasestorage.app',
    iosClientId: '497752609770-01l1dgpbdk4i101escs0plcv06clqfuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.deshCrimeAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjd4mELmwtCaWJHUrb7l6x8pM1dbZfLE',
    appId: '1:497752609770:web:bcdb7a5733817a5aa51893',
    messagingSenderId: '497752609770',
    projectId: 'desh-crime-alert-e1b7a',
    authDomain: 'desh-crime-alert-e1b7a.firebaseapp.com',
    storageBucket: 'desh-crime-alert-e1b7a.firebasestorage.app',
    measurementId: 'G-JGS3B8Q7F6',
  );
}
